version: "3.7"

services:
  revolutapp:
    build: ./app
    image: gdury/revolut-app:master-b7b724
    ports:
      - "3000:3000"
    networks:
      - overlay
    depends_on:
      - postgres
    env_file:
      - .app
  postgres:
    build: ./postgres
    image: gdury/custom-postgresql:latest
    networks:
       - overlay
    env_file:
      - .db
    ports:
      - "5432:5432"

networks:
  overlay:

